name: Test Server

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: latest
      - run: npm run test
